Yaroslav Brish: homework 27 completed
eugene-okulik/brishar pull request #25
Opened 2024-09-26 19:36 UTC by yaroslavbrish

2024-09-27 08:34 UTC, eugene-okulik requested changes

2024-09-27 08:34 UTC, eugene-okulik commented on homework/yaroslav_brish/Homework_27/hw27_exercise_3.py
> +    expect(clickable_button).to_be_enabled()
Задание было 

> только после того как она станет красной

а не "после того, как какая-то другая кнопка станет активной"

2024-09-27 16:18 UTC, yaroslavbrish commented
хах, самое интересное, что я изначально так и сделал, но меня потом что-то переклинило и я решил: "ну кнопка Color Change появляется только после того, как первая кнопка становится кликабельной - значит нужно дождаться, пока она станет кликабельной..."
короче, сам себя перемудрил)

2024-09-27 16:19 UTC, yaroslavbrish commented on homework/yaroslav_brish/Homework_27/hw27_exercise_3.py
> +    expect(clickable_button).to_be_enabled()
хах, самое интересное, что я изначально так и сделал, но меня потом что-то переклинило и я решил: "ну кнопка Color Change появляется только после того, как первая кнопка становится кликабельной - значит нужно дождаться, пока она станет кликабельной..."
короче, сам себя перемудрил)

2024-09-29 09:11 UTC, eugene-okulik commented on homework/yaroslav_brish/Homework_27/hw27_exercise_3.py
> +    expect(clickable_button).to_be_enabled()
бывает )))

2024-09-29 09:12 UTC, eugene-okulik approved these changes

2024-09-29 09:12 UTC, merged