Yaroslav Brish: homework 29 completed
eugene-okulik/brishar pull request #27
Opened 2024-10-08 19:49 UTC by yaroslavbrish

2024-10-09 08:48 UTC, eugene-okulik requested changes

2024-10-09 08:48 UTC, eugene-okulik commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/create_account_page.py
> +        self.find(loc.create_button_loc).click()
Хорошо бы, чтобы из названия было понятно что за кнопку кликает этот метод.

2024-10-09 08:48 UTC, eugene-okulik commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/create_account_page.py
> +            "There is already an account with this email address"
Это - тестовые данные. Метод должен принимать этот текст из теста и проверять, что он есть в этом алерте.

2024-10-09 08:48 UTC, eugene-okulik commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/eco_friendly_page.py
> +        product = self.find(loc.product_loc)
Раз ты работаешь только с одним конкретным элементом и не даешь возможности кликать по другим, этот метод должен называться click_on_ana_running_short. Но этого товара в какой-то момент может не оказаться в магазине - и тогда твой тест упадет. Правильнее делать метод, который из теста принимает что ему там нужно кликнуть. То же самое касается и методов ниже - они все заточены под один конкретный товар. И нужно или отобразить это в названии методов или сделать методы универсальными.

2024-10-09 08:48 UTC, eugene-okulik commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/sale_page.py
> +        women_sale.click()
Этот метод кликает по элементу woman sale. Хорошо бы, чтобы из название метода было понятно, что этот метод делает не woman sale, а он кликает по woman sale

2024-10-09 08:48 UTC, eugene-okulik commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/sale_page.py
> +        gear.click()
И эти названия тоже просятся быть измененными.

2024-10-09 17:45 UTC, yaroslavbrish commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/create_account_page.py
> +        self.find(loc.create_button_loc).click()
изменил название на click_create_button

2024-10-09 17:46 UTC, yaroslavbrish commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/create_account_page.py
> +            "There is already an account with this email address"
теперь текст принимается из теста и проверяет, есть ли он в алерте

2024-10-09 17:48 UTC, yaroslavbrish commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/eco_friendly_page.py
> +        product = self.find(loc.product_loc)
сделал тест универсальным + разбил функцию "add_to_cart" на несколько более мелких функций.
теперь в тесте указывается номер продукт айтема, на который нужно навестись. и уже для наведенного айтема выбирается, какой размер и какой цвет выбрать.
всё реализовал через .nth()

2024-10-09 17:48 UTC, yaroslavbrish commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/eco_friendly_page.py
> +        product = self.find(loc.product_loc)
поменял название на women_sale_click

2024-10-09 17:49 UTC, yaroslavbrish commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/sale_page.py
> +        women_sale.click()
поменял название на women_sale_click

2024-10-09 17:49 UTC, yaroslavbrish commented on homework/yaroslav_brish/test_UI_ybrish_pw/pages/sale_page.py
> +        gear.click()
поменял названия на men_sale_click и gear_click соответственно

2024-10-09 17:52 UTC, yaroslavbrish commented
@eugene-okulik про изменения в новом коде ответил под каждым из твоих комментов выше

2024-10-10 08:29 UTC, eugene-okulik approved these changes
:+1:

2024-10-10 08:29 UTC, merged