Yaroslav Brish: Homework 4 completed
eugene-okulik/brishar pull request #3
Opened 2024-05-17 16:28 UTC by yaroslavbrish

2024-05-18 12:25 UTC, eugene-okulik approved these changes
Всё отлично, но одну проверку на внимательность не прошел ))

2024-05-18 12:25 UTC, eugene-okulik commented on homework/yaroslav_brish/Homework_4/hw4_excercise_1.py
> +my_dict['dict'].update({'i am a tuple': 'WTF'})
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-05-18 12:25 UTC, eugene-okulik requested changes
Случайно апрувнул, исправляюсь ))

2024-05-18 18:24 UTC, yaroslavbrish commented on homework/yaroslav_brish/Homework_4/hw4_excercise_1.py
> +my_dict['dict'].update({'i am a tuple': 'WTF'})
блииин, точняк! подловил)
а я еще смотрел на эту запятую после ковыче и не мог понять, опечатка это (баг) или нет. В итоге просто без запятой скопировал стрингу 🤣

2024-05-20 15:30 UTC, eugene-okulik approved these changes

2024-05-20 15:30 UTC, merged